### PR TITLE
Adding Application Insights integration

### PR DESCRIPTION
**Pull request by eladiw**

### CODE REVIEW

**Comment by eladiw** [comment]
Work was done in collaboration with @fcatae

**Comment by lawrencegripper** [comment]
Picking this up now to test out.

**Comment by eladiw** [comment]
@lawrencegripper , Done

**Comment by ldez** [comment]
@lawrencegripper it's not required to include `github.com/jjcollinge/logrus-appinsights` in `gopkg.toml`: `gopkg.toml` contains only constrained dependencies.
If you want to use a specific branch or version, it's required but not in this case.

A simple `dep ensure -v` do the job in this case.

**Comment by lawrencegripper** [comment]
@ldez thanks, I had been working on the assumption that constraining dependencies was a good best practice to prevent unexpected breaking changes when running `dep ensure` in the future. Is there a good guide I can read on when you should constrain vs not?

**Comment by ldez** [comment]
`dep ensure` don't update dependencies, it only download dependencies define in the lock file.

To update a dependencies `dep ensure --update xxxxx/foo` for one dep and `dep ensure --update` to update all.

The basic constraint is the lock file. It's the "lock way" like yarn or npm.

The constraints are used when:
- a dependency have a very old tag (unmaintained semver)
- you want to use a specific version
- you want to use a specific branch
- you want to constraint a client of a lib to use the HEAD of branch (I don't recommend that).

**Comment by AlexandruRus23** [comment]
Hello,

I can see that this is merged and delivered with Traefik 1.7, but after adding application insights instance name and instrumentation key I only find Traefik logs in application insights traces.

Unfortunately the documentation does not appear to be up to date, but is there a way of configuring it to also show access logs?

Sorry if I'm not posting this where I should.

**Comment by lawrencegripper** [comment]
This PR added support for shipping application logs to AppInsights but I don't believe it included shipping access logs @jjcollinge and @eladiw look at this in more detail and will hopefully be able to provide some more info.

**Pull request merged**
