### PR TITLE
Add SameSite, HTTPOnly, Secure cookie support (v1.7)

### PR DESCRIPTION
**Pull request by tpayne84**
1. Update traefik dependency to latest v1.7 changes.
2. Update servicefabric provider template to include the [SameSite, HTTPOnly, Secure] labels under LoadBalancer.Stickiness.

Related to https://github.com/traefik/traefik/pull/7667

### CODE REVIEW

**Comment by tpayne84** [comment]
I see the build for this has failed, though I do not see how my changes are related. Perhaps they are and I am missing it, but this open issue looks to be related; [context loading failed: no go files to analyze](https://github.com/golangci/golangci-lint/issues/825)

Either way, any guidance on how best update this PR for approval is appreciated.

**Comment by ldez** [comment]
The update of this part is a bit complex, I will help you with this.
I just have to find a bit of time to handle that.

**Comment by tpayne84** [comment]
@ldez Great, I will review your suggestions once you have had an opportunity to generate a response (no rush).

Thanks!

**Review by ldez — APPROVED** [review]
Thanks :+1:

**Pull request merged**
