### PR TITLE
Provide easy way to test Traefik Provider against Service Fabric with Docker

### PR DESCRIPTION
**Pull request by lawrencegripper**
This PR adds a simple way to start a cluster inside a docker image, with apps running, to test the behavior of the provider.  

Related to #7

### CODE REVIEW

**Comment by ldez** [comment]
To be consistent with Træfik could you rename `integrationtesting/` to `integration/` ?

**Comment by lawrencegripper** [comment]
Done, I've added a note to the readme.md as you need to add the following to your docker daemon settings for the cluster to behave:

```json
{
    "ipv6": true,
    "fixed-cidr-v6": "fd00::/64"
}
```

**Comment by lawrencegripper** [comment]
@ldez I've been looking at the existing integration tests in the Traefik repo and could use some guidance. 

Would you preference be for me to use `github.com/libkermit/compose/check` to start the SF docker image running the cluster then start the traefik binary? 

My first thought was to write a test which starts the container then invoke the `provide` function on the sf provider and ensure the configuration returned was as expected. I'd also like to write a further test where labels are then altered using the SF API and validate the configuration change is picked up. Does this sound like a good plan?

**Comment by lawrencegripper** [comment]
Closing as stale and very out of date now

**Pull request closed without merging**
